import { describe, expect, test } from 'bun:test';
import { injectRoot } from '../lib/memory-inject.mjs';

describe('injectRoot', () => {
  test('inserts ROOT with markers into existing MEMORY.md', () => {
    const existing = [
      '# Memory',
      '',
      '## User Preferences',
      '',
      '- Dark mode enabled',
    ].join('\n');

    const result = injectRoot(existing, 'topic: auth\ntopic: deploy');

    expect(result).toContain('<!-- ENGRAM-BEGIN -->');
    expect(result).toContain('<!-- ENGRAM-END -->');
    expect(result).toContain('topic: auth');
    expect(result).toContain('topic: deploy');
    expect(result).toContain('## ROOT (auto-generated by engram)');
  });

  test('replaces existing ROOT section between markers', () => {
    const existing = [
      '# Memory',
      '',
      '## ROOT (auto-generated by engram)',
      '<!-- ENGRAM-BEGIN -->',
      'old-topic: stale-data',
      '<!-- ENGRAM-END -->',
      '',
      '## User Preferences',
      '',
      '- Dark mode enabled',
    ].join('\n');

    const result = injectRoot(existing, 'new-topic: fresh-data');

    expect(result).toContain('new-topic: fresh-data');
    expect(result).not.toContain('old-topic: stale-data');
    // Markers should appear exactly once each
    expect(result.split('<!-- ENGRAM-BEGIN -->').length).toBe(2);
    expect(result.split('<!-- ENGRAM-END -->').length).toBe(2);
  });

  test('creates structure when content is empty', () => {
    const result = injectRoot('', 'topic: init');

    expect(result).toContain('# Memory');
    expect(result).toContain('## ROOT (auto-generated by engram)');
    expect(result).toContain('<!-- ENGRAM-BEGIN -->');
    expect(result).toContain('topic: init');
    expect(result).toContain('<!-- ENGRAM-END -->');
  });

  test('creates structure when content is null/undefined', () => {
    const result = injectRoot(null, 'topic: null-safe');

    expect(result).toContain('# Memory');
    expect(result).toContain('topic: null-safe');
  });

  test('preserves User Preferences and other sections', () => {
    const existing = [
      '# Memory',
      '',
      '## User Preferences',
      '',
      '- Prefers immutable patterns',
      '- Uses bun runtime',
      '',
      '## Project References',
      '',
      '- JIRA: https://jira.example.com/',
    ].join('\n');

    const result = injectRoot(existing, 'topic: testing');

    expect(result).toContain('## User Preferences');
    expect(result).toContain('- Prefers immutable patterns');
    expect(result).toContain('- Uses bun runtime');
    expect(result).toContain('## Project References');
    expect(result).toContain('- JIRA: https://jira.example.com/');
    expect(result).toContain('topic: testing');
  });

  test('truncates ROOT content to stay within 200 lines', () => {
    const existingLines = [
      '# Memory',
      '',
      '## User Preferences',
      '',
      ...Array.from({ length: 50 }, (_, i) => `- pref ${i}`),
    ];
    const existing = existingLines.join('\n');

    // Generate ROOT content that would exceed 200 lines total
    const bigRoot = Array.from({ length: 180 }, (_, i) => `line-${i}`).join('\n');

    const result = injectRoot(existing, bigRoot);
    const totalLines = result.split('\n').length;

    expect(totalLines).toBeLessThanOrEqual(200);
    // Should still contain at least some ROOT content
    expect(result).toContain('line-0');
  });

  test('handles MEMORY.md with content but no "# Memory" header', () => {
    const existing = [
      '## Some Random Section',
      '',
      'Content without a proper header.',
    ].join('\n');

    const result = injectRoot(existing, 'topic: no-header');

    // Should create the full structure since there's no "# Memory"
    expect(result).toContain('# Memory');
    expect(result).toContain('<!-- ENGRAM-BEGIN -->');
    expect(result).toContain('topic: no-header');
    expect(result).toContain('<!-- ENGRAM-END -->');
  });

  test('replacement preserves content after END marker', () => {
    const existing = [
      '# Memory',
      '',
      '## ROOT (auto-generated by engram)',
      '<!-- ENGRAM-BEGIN -->',
      'old content',
      '<!-- ENGRAM-END -->',
      '',
      '## Feedback',
      '',
      '- Important feedback here',
    ].join('\n');

    const result = injectRoot(existing, 'replaced content');

    expect(result).toContain('replaced content');
    expect(result).not.toContain('old content');
    expect(result).toContain('## Feedback');
    expect(result).toContain('- Important feedback here');
  });
});
