import { join, dirname } from 'path';
import { homedir } from 'os';
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { resolveProject, findProjectDirs, getProjectsDir } from '../lib/resolve.mjs';

const HOME = homedir();
const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..');

// slice(3) skips: [0] bun, [1] main.mjs, [2] "init"
const args = process.argv.slice(3).filter(a => !a.startsWith('--'));
const projectArg = process.argv.includes('--project')
  ? process.argv[process.argv.indexOf('--project') + 1]
  : null;

console.log('engram init\n');

// 1. Check bun
try {
  execSync('bun --version', { stdio: 'ignore' });
  console.log('[ok] Bun installed');
} catch {
  console.error('[!!] Bun not found. Install from: https://bun.sh');
  process.exit(1);
}

// 2. Detect project from ~/.claude/projects/
const projectsDir = getProjectsDir();
let project = projectArg;

if (!project) {
  if (!existsSync(projectsDir)) {
    console.error('[!!] No ~/.claude/projects/ directory found. Run Claude Code first.');
    process.exit(1);
  }

  const candidates = readdirSync(projectsDir, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('.'))
    .map(d => d.name)
    .filter(name => {
      // Only include dirs that have JSONL files
      try {
        return readdirSync(join(projectsDir, name)).some(f => f.endsWith('.jsonl'));
      } catch { return false; }
    });

  if (candidates.length === 0) {
    console.error('[!!] No projects with sessions found. Specify --project <name>');
    process.exit(1);
  }

  // Resolve to short names and deduplicate
  const resolved = new Map();
  for (const c of candidates) {
    const short = resolveProject(c);
    if (!resolved.has(short)) resolved.set(short, c);
  }

  if (resolved.size === 1) {
    const [short, raw] = [...resolved.entries()][0];
    project = short;
  } else {
    console.log('Available projects:');
    let i = 1;
    for (const [short, raw] of resolved) {
      const count = readdirSync(join(projectsDir, raw)).filter(f => f.endsWith('.jsonl')).length;
      console.log(`  ${i++}. ${short} (${count} sessions)`);
    }
    console.error('\nSpecify: engram init --project <name>');
    process.exit(1);
  }
}

console.log(`[ok] Project: ${project}`);

// 3. Create directories
const compactionDir = join(HOME, '.claude', 'compaction', project, 'monthly');
mkdirSync(compactionDir, { recursive: true });
console.log(`[ok] Created: ~/.claude/compaction/${project}/monthly/`);

// 4. Initialize .state.json
const stateFile = join(HOME, '.claude', 'compaction', project, '.state.json');
if (!existsSync(stateFile)) {
  writeFileSync(stateFile, JSON.stringify({
    schema_version: 1,
    last_run: null,
    project,
    project_dir: null,
    monthly_nodes: {},
  }, null, 2));
  console.log('[ok] Initialized .state.json');
}

// 5. Find and update MEMORY.md (insert ENGRAM markers)
const matchingDirs = findProjectDirs(project, projectsDir);
for (const pd of matchingDirs) {
  const memoryDir = join(projectsDir, pd, 'memory');
  const memoryPath = join(memoryDir, 'MEMORY.md');

  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true });
  }

  if (existsSync(memoryPath)) {
    const content = readFileSync(memoryPath, 'utf-8');
    if (!content.includes('ENGRAM-BEGIN')) {
      const marker = '\n## ROOT (auto-generated by engram)\n<!-- ENGRAM-BEGIN -->\n(run engram compact to populate)\n<!-- ENGRAM-END -->\n';
      const memoryIdx = content.indexOf('# Memory');
      let updated;
      if (memoryIdx >= 0) {
        const afterHeader = content.indexOf('\n', memoryIdx);
        updated = content.slice(0, afterHeader + 1) + marker + content.slice(afterHeader + 1);
      } else {
        updated = '# Memory\n' + marker + '\n' + content;
      }
      writeFileSync(memoryPath, updated, 'utf-8');
      console.log(`[ok] ROOT markers inserted into ${pd}/memory/MEMORY.md`);
    } else {
      console.log(`[ok] ROOT markers already exist in ${pd}/memory/MEMORY.md`);
    }
  } else {
    const content = '# Memory\n\n## ROOT (auto-generated by engram)\n<!-- ENGRAM-BEGIN -->\n(run engram compact to populate)\n<!-- ENGRAM-END -->\n';
    writeFileSync(memoryPath, content, 'utf-8');
    console.log(`[ok] MEMORY.md created with ROOT markers in ${pd}/memory/`);
  }
}

// 6. Configure hooks in settings.json
const settingsPath = join(HOME, '.claude', 'settings.json');
const bunCmd = `"\${HOME}/.bun/bin/bun" "\${HOME}/workspace/engram/cli/main.mjs"`;
const hookDefs = {
  SessionStart: { command: `${bunCmd} hook session-start`, timeout: 30 },
  SessionEnd:   { command: `${bunCmd} hook session-end`,   timeout: 30 },
};

let hookInstalled = false;
if (existsSync(settingsPath)) {
  const settings = JSON.parse(readFileSync(settingsPath, 'utf-8'));
  if (!settings.hooks) settings.hooks = {};
  let changed = false;

  for (const [event, def] of Object.entries(hookDefs)) {
    if (!settings.hooks[event]) settings.hooks[event] = [];
    const has = settings.hooks[event].some(entry =>
      entry.hooks?.some(h => h.command && h.command.includes('engram'))
    );
    if (!has) {
      settings.hooks[event].push({ hooks: [{ type: 'command', ...def }] });
      changed = true;
    }
  }

  if (changed) {
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
    console.log('[ok] Hooks added to ~/.claude/settings.json');
  } else {
    console.log('[ok] Hooks already configured');
  }
  hookInstalled = true;
} else {
  const settings = { hooks: {} };
  for (const [event, def] of Object.entries(hookDefs)) {
    settings.hooks[event] = [{ hooks: [{ type: 'command', ...def }] }];
  }
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
  console.log('[ok] Created ~/.claude/settings.json with hooks');
  hookInstalled = true;
}

// 7. Register QMD collection (optional)
try {
  execSync('qmd --version', { stdio: 'ignore' });
  const collectionName = `${project}-compaction`;
  try {
    execSync(`qmd collection show "${collectionName}" 2>/dev/null`, { stdio: 'ignore' });
    console.log(`[ok] QMD collection ${collectionName} exists`);
  } catch {
    try {
      const compDir = join(HOME, '.claude', 'compaction', project);
      execSync(`cd "${compDir}" && qmd collection add "${collectionName}"`, { stdio: 'pipe' });
      console.log(`[ok] QMD collection ${collectionName} registered`);
    } catch (e) {
      console.log(`[warn] Could not register QMD collection: ${e.message}`);
    }
  }
} catch {
  console.log('[skip] QMD not installed (optional — BM25/vector search disabled)');
}

// 8. Install skills
const skillSource = join(PACKAGE_ROOT, 'skills', 'compaction', 'SKILL.md');
const skillDest = join(HOME, '.claude', 'skills', 'engram-compaction');
mkdirSync(skillDest, { recursive: true });
if (existsSync(skillSource)) {
  copyFileSync(skillSource, join(skillDest, 'SKILL.md'));
  console.log('[ok] Compaction skill installed');
}

const recallSource = join(PACKAGE_ROOT, 'skills', 'recall');
const recallDest = join(HOME, '.claude', 'skills', 'engram-recall');
if (existsSync(join(recallSource, 'SKILL.md'))) {
  const copyDirRecursive = (src, dest) => {
    mkdirSync(dest, { recursive: true });
    for (const entry of readdirSync(src, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || entry.name === '__pycache__' || entry.name === 'CLAUDE.md') continue;
      const srcPath = join(src, entry.name);
      const destPath = join(dest, entry.name);
      if (entry.isDirectory()) {
        copyDirRecursive(srcPath, destPath);
      } else {
        copyFileSync(srcPath, destPath);
      }
    }
  };
  copyDirRecursive(recallSource, recallDest);
  console.log('[ok] Recall skill installed');
}

// 9. Run initial compaction for all matching project dirs
console.log('\n[..] Running initial compaction (--full)...');
for (const pd of matchingDirs) {
  try {
    const output = execSync(`bun "${join(__dirname, 'main.mjs')}" compact "${pd}" --full`, {
      encoding: 'utf-8',
      timeout: 60000,
    });
    console.log(output.trim());
  } catch (e) {
    console.log(`[warn] Compaction failed for ${pd}: ${e.message}`);
  }
}

console.log('\n[done] engram initialized for ' + project);
console.log('\nWhat was set up:');
console.log('  - Compaction output: ~/.claude/compaction/' + project + '/');
console.log('  - MEMORY.md markers: ENGRAM-BEGIN/END for ROOT injection');
if (hookInstalled) {
  console.log('  - SessionStart hook: auto-update version check');
  console.log('  - SessionEnd hook: auto-compact on session end');
}
console.log('\nNext steps:');
console.log('  1. Start a new Claude Code session to see ROOT.md in your context');
console.log('  2. engram status to check compaction state');
