import { join, dirname } from 'path';
import { homedir } from 'os';
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const HOME = homedir();
const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..');

const args = process.argv.slice(2).filter(a => !a.startsWith('--'));
const projectArg = process.argv.includes('--project')
  ? process.argv[process.argv.indexOf('--project') + 1]
  : null;

console.log('engram init\n');

// 1. Check QMD
try {
  execSync('qmd --version', { stdio: 'ignore' });
  console.log('[ok] QMD installed');
} catch {
  console.error('[!!] QMD not found. Install with: bun add -g @tobilu/qmd');
  process.exit(1);
}

// 2. Detect project
const sessionsBase = join(HOME, '.claude', 'sessions-md');
let project = projectArg;

if (!project) {
  if (!existsSync(sessionsBase)) {
    console.error('[!!] No sessions-md directory found. Specify --project <name>');
    process.exit(1);
  }
  const candidates = readdirSync(sessionsBase).filter(d => {
    return !d.startsWith('.') && !d.startsWith('-');
  });

  if (candidates.length === 0) {
    console.error('[!!] No projects found in sessions-md. Specify --project <name>');
    process.exit(1);
  }

  if (candidates.length === 1) {
    project = candidates[0];
  } else {
    console.log('Available projects:');
    candidates.forEach((c, i) => console.log(`  ${i + 1}. ${c}`));
    console.error('\nSpecify: engram init --project <name>');
    process.exit(1);
  }
}

console.log(`[ok] Project: ${project}`);

// 3. Create directories
const compactionDir = join(HOME, '.claude', 'compaction', project, 'monthly');
mkdirSync(compactionDir, { recursive: true });
console.log(`[ok] Created: ~/.claude/compaction/${project}/monthly/`);

// 4. Initialize .state.json
const stateFile = join(HOME, '.claude', 'compaction', project, '.state.json');
if (!existsSync(stateFile)) {
  writeFileSync(stateFile, JSON.stringify({
    schema_version: 1,
    last_run: null,
    project,
    project_dir: null,
    monthly_nodes: {},
  }, null, 2));
  console.log('[ok] Initialized .state.json');
}

// 5. Find and update MEMORY.md
const projectsDir = join(HOME, '.claude', 'projects');
if (existsSync(projectsDir)) {
  const projectDirs = readdirSync(projectsDir).filter(d =>
    d.includes(project) && existsSync(join(projectsDir, d, 'memory'))
  );

  for (const pd of projectDirs) {
    const memoryPath = join(projectsDir, pd, 'memory', 'MEMORY.md');
    if (existsSync(memoryPath)) {
      const content = readFileSync(memoryPath, 'utf-8');
      if (!content.includes('ENGRAM-BEGIN')) {
        // Insert ROOT markers after # Memory (or at top)
        const marker = '\n## ROOT (auto-generated by engram)\n<!-- ENGRAM-BEGIN -->\n(run engram compact to populate)\n<!-- ENGRAM-END -->\n';

        const memoryIdx = content.indexOf('# Memory');
        let updated;
        if (memoryIdx >= 0) {
          const afterHeader = content.indexOf('\n', memoryIdx);
          updated = content.slice(0, afterHeader + 1) + marker + content.slice(afterHeader + 1);
        } else {
          updated = '# Memory\n' + marker + '\n' + content;
        }
        writeFileSync(memoryPath, updated, 'utf-8');
        console.log(`[ok] ROOT markers inserted into ${pd}/memory/MEMORY.md`);
      } else {
        console.log(`[ok] ROOT markers already exist in ${pd}/memory/MEMORY.md`);
      }
    }
  }
}

// 6. Modify stop-hook.sh
const stopHook = join(HOME, '.claude', 'scripts', 'stop-hook.sh');
if (existsSync(stopHook)) {
  const hookContent = readFileSync(stopHook, 'utf-8');
  if (!hookContent.includes('engram')) {
    // Insert before the "qmd embed" line (or at end)
    const embedIdx = hookContent.indexOf('nohup qmd embed');
    const insertLine = '\n# engram: monthly compaction + ROOT.md\nif command -v engram >/dev/null 2>&1; then\n  engram compact "$PROJECT_DIR" 2>/dev/null || true\nfi\n';

    let updated;
    if (embedIdx >= 0) {
      updated = hookContent.slice(0, embedIdx) + insertLine + '\n' + hookContent.slice(embedIdx);
    } else {
      updated = hookContent + insertLine;
    }
    writeFileSync(stopHook, updated, 'utf-8');
    console.log('[ok] stop-hook.sh updated');
  } else {
    console.log('[ok] stop-hook.sh already has engram');
  }
} else {
  console.log('[warn] stop-hook.sh not found, skipping');
}

// 7. Register QMD collection
const collectionName = `${project}-compaction`;
try {
  execSync(`qmd collection show "${collectionName}" 2>/dev/null`, { stdio: 'ignore' });
  console.log(`[ok] QMD collection ${collectionName} exists`);
} catch {
  try {
    const compDir = join(HOME, '.claude', 'compaction', project);
    execSync(`cd "${compDir}" && qmd collection add "${collectionName}"`, { stdio: 'pipe' });
    console.log(`[ok] QMD collection ${collectionName} registered`);
  } catch (e) {
    console.log(`[warn] Could not register QMD collection: ${e.message}`);
  }
}

// 8. Install compaction skill
const skillSource = join(PACKAGE_ROOT, 'skills', 'compaction', 'SKILL.md');
const skillDest = join(HOME, '.claude', 'skills', 'engram-compaction');
mkdirSync(skillDest, { recursive: true });
if (existsSync(skillSource)) {
  copyFileSync(skillSource, join(skillDest, 'SKILL.md'));
  console.log('[ok] Compaction skill installed');
} else {
  console.log('[warn] Skill source not found, skipping');
}

// 8b. Install recall skill (SKILL.md + scripts + workflows + venv)
const recallSource = join(PACKAGE_ROOT, 'skills', 'recall');
const recallDest = join(HOME, '.claude', 'skills', 'engram-recall');
if (existsSync(join(recallSource, 'SKILL.md'))) {
  // Copy directory tree recursively (SKILL.md, scripts/, workflows/)
  const copyDirRecursive = (src, dest) => {
    mkdirSync(dest, { recursive: true });
    for (const entry of readdirSync(src, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || entry.name === '__pycache__' || entry.name === 'CLAUDE.md') continue;
      const srcPath = join(src, entry.name);
      const destPath = join(dest, entry.name);
      if (entry.isDirectory()) {
        copyDirRecursive(srcPath, destPath);
      } else {
        copyFileSync(srcPath, destPath);
      }
    }
  };
  copyDirRecursive(recallSource, recallDest);
  console.log('[ok] Recall skill installed');

  // Setup Python venv + install dependencies
  const venvPath = join(recallDest, '.venv');
  if (!existsSync(venvPath)) {
    try {
      execSync(`python3 -m venv "${venvPath}"`, { stdio: 'pipe', timeout: 30000 });
      execSync(`"${join(venvPath, 'bin', 'pip3')}" install -r "${join(recallDest, 'requirements.txt')}"`, {
        stdio: 'pipe',
        timeout: 120000,
      });
      console.log('[ok] Recall venv created + dependencies installed');
    } catch (e) {
      console.log(`[warn] Recall venv setup failed: ${e.message}`);
    }
  } else {
    console.log('[ok] Recall venv already exists');
  }
} else {
  console.log('[warn] Recall skill source not found, skipping');
}

// 9. Run initial compaction
console.log('\n[..] Running initial compaction (--full)...');
try {
  const output = execSync(`bun "${join(__dirname, 'main.mjs')}" compact "${project}" --full`, {
    encoding: 'utf-8',
    timeout: 60000,
  });
  console.log(output.trim());
} catch (e) {
  console.log(`[warn] Initial compaction failed: ${e.message}`);
}

console.log('\n[done] engram initialized for ' + project);
console.log('\nNext steps:');
console.log('  1. Run "bun link" in this directory to make engram globally available');
console.log('  2. Start a new Claude Code session to see ROOT.md in your context');
console.log('  3. engram status to check compaction state');
