/**
 * MEMORY.md ROOT section injection module.
 *
 * injectRoot(existingMemoryContent, rootContent) - Replace or insert the
 * auto-generated ROOT section in MEMORY.md while preserving all other content.
 */

const MARKER_BEGIN = '<!-- ENGRAM-BEGIN -->';
const MARKER_END = '<!-- ENGRAM-END -->';
const ROOT_HEADING = '## ROOT (auto-generated by engram)';
const MAX_TOTAL_LINES = 200;

/**
 * Build the ROOT section block from the given content.
 *
 * @param {string} rootContent - The body to place between markers.
 * @returns {string} Full ROOT section including heading and markers.
 */
function buildRootSection(rootContent) {
  return [
    ROOT_HEADING,
    MARKER_BEGIN,
    rootContent,
    MARKER_END,
  ].join('\n');
}

/**
 * Truncate rootContent lines so the total output stays within MAX_TOTAL_LINES.
 *
 * @param {string[]} outerLines - Lines outside the ROOT section.
 * @param {string}   rootContent - The ROOT body content.
 * @returns {string} Possibly truncated rootContent.
 */
function truncateIfNeeded(outerLines, rootContent) {
  // The ROOT section adds 3 fixed lines: heading, begin marker, end marker
  const fixedOverhead = 3;
  const budget = MAX_TOTAL_LINES - outerLines.length - fixedOverhead;

  if (budget <= 0) {
    return '(truncated)';
  }

  const contentLines = rootContent.split('\n');
  if (contentLines.length <= budget) {
    return rootContent;
  }

  return contentLines.slice(0, budget).join('\n');
}

/**
 * Replace or insert a ROOT section in MEMORY.md content.
 *
 * Strategy (in priority order):
 *   1. If ENGRAM markers exist, replace content between them.
 *   2. If "# Memory" heading exists but no markers, insert ROOT after it.
 *   3. If content is empty or has no "# Memory", create full structure.
 *
 * The total output is capped at 200 lines; ROOT content is truncated if needed.
 *
 * @param {string} existingMemoryContent - Current MEMORY.md content (may be empty).
 * @param {string} rootContent           - New ROOT body to inject.
 * @returns {string} Updated MEMORY.md content.
 */
export function injectRoot(existingMemoryContent, rootContent) {
  const existing = existingMemoryContent ?? '';

  // --- Case 1: markers already present ---
  const beginIdx = existing.indexOf(MARKER_BEGIN);
  const endIdx = existing.indexOf(MARKER_END);

  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const before = existing.slice(0, beginIdx + MARKER_BEGIN.length);
    const after = existing.slice(endIdx);

    // outer = before (includes begin marker) + after (includes end marker)
    // The result will be: before + \n + truncated + \n + after
    // So total lines = outerLines + contentLines + 1 (the extra \n join)
    const outerLines = (before + '\n' + after).split('\n');
    const budget = MAX_TOTAL_LINES - outerLines.length - 1; // -1 for the joining newline
    const contentLines = rootContent.split('\n');
    const truncated = contentLines.length <= budget
      ? rootContent
      : contentLines.slice(0, Math.max(1, budget)).join('\n');

    return before + '\n' + truncated + '\n' + after;
  }

  // --- Case 2: "# Memory" heading exists but no markers ---
  const memoryHeadingRe = /^# Memory\s*$/m;
  const memoryMatch = memoryHeadingRe.exec(existing);

  if (memoryMatch) {
    const insertPos = memoryMatch.index + memoryMatch[0].length;
    const before = existing.slice(0, insertPos);
    const after = existing.slice(insertPos);

    // The result will be: before + \n\n + heading + \n + begin + \n + content + \n + end + \n + after
    // overhead = before lines + after lines + 2 (blank+heading) + 2 (begin+end) + 2 (join newlines)
    const outerLineCount = before.split('\n').length + after.split('\n').length;
    const overhead = 4 + 2; // heading, begin, end markers + blank lines and joins
    const budget = MAX_TOTAL_LINES - outerLineCount - overhead;
    const contentLines = rootContent.split('\n');
    const truncatedContent = budget <= 0
      ? '(truncated)'
      : contentLines.length <= budget
        ? rootContent
        : contentLines.slice(0, Math.max(1, budget)).join('\n');
    const section = buildRootSection(truncatedContent);

    return before + '\n\n' + section + '\n' + after;
  }

  // --- Case 3: empty or no "# Memory" header ---
  const scaffold = '# Memory';
  const outerLines = [scaffold, ''];
  const truncated = truncateIfNeeded(outerLines, rootContent);
  const section = buildRootSection(truncated);

  return scaffold + '\n\n' + section + '\n';
}
